version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: devops
      MYSQL_ROOT_PASSWORD: ""  # Set a strong password for production
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  springboot:
    build:
      context: ./Backend  # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile  # Ensure this is the correct name of your Dockerfile
    container_name: springboot
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/devops
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""  # Set a strong password for production
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - app-network

  angular:
    build:
      context: ./Frontend  # Path to your Angular Dockerfile
      dockerfile: Dockerfile  # Ensure this is the correct name of your Dockerfile
    container_name: angular
    ports:
      - "80:80"
    depends_on:
      - springboot
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
