version: "3"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: devops
      MYSQL_ALLOW_EMPTY_PASSWORD: root  # Allow empty password
    ports:
      - "3306:3306"  # Host port: 3306, Container port: 3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  springboot:
    build:
      context: ./Backend  # Path to the Spring Boot Dockerfile
      dockerfile: Dockerfile
    container_name: springboot
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/devops  # MySQL service name used as hostname
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""  # Empty password
    ports:
      - "8085:8080"  # Host port: 8085, Container port: 8080
    depends_on:
      - mysql
    networks:
      - app-network

  angular:
    build:
      context: ./Frontend  # Path to the Angular Dockerfile
      dockerfile: Dockerfile
    container_name: angular
    ports:
      - "80:80"  # Angular app on port 80 for easy access
    depends_on:
      - springboot
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    external: true
